### ISSUE TITLE
Finger imports to large causing blender to ram usage to shoot up to 20GB at render times

### ISSUE THREAD

**Issue by BAProductions** [butaixianran/DazToBlender#4]
Finger imports to large causing blender to ram usage to shoot up to 20GB at render times

**Comment by butaixianran** [comment]
What you mean "Finger imports", import a Daz model with hand won't has the issue you mentioned.

**Comment by BAProductions** [comment]
> What you mean "Finger imports", import a Daz model with hand won't has the issue you mentioned.

This is a new issue, Finger imports at a different scale the the environment Finger place in AKA my Finger bigger then the sofa she sitting on. Sofa to small an Finger to large.

**Comment by butaixianran** [comment]
Still don't understand. What you mean Finger here, do you mean figure? You better upload some images to show your issue.
