### ISSUE TITLE
How to Install to Daz Studio 4.21?

### ISSUE THREAD

**Issue by UuuNyaa** [butaixianran/DazToBlender#5]
I tried to install DFB according to [README.md](https://github.com/butaixianran/DazToBlender/blob/cb9d5c98c1d61d61720d680613ebf127e429b53f/README.md), but the directories I seek does not exist in the Daz Studio 4.21.

```
find C:/ -name '*DAZStudio4*'                                                                                                                       ✔  16:21:39  
C:/Daz 3D/Applications/Data/DAZ 3D/InstallManager/ManifestFiles/IM00013176-02_DAZStudio421Win64bit.dsx
C:/Daz 3D/Applications/Data/DAZ 3D/InstallManager/ManifestFiles/IM00013176-42_DefaultResourcesforDAZStudio420.dsx
C:/Daz 3D/Applications/Data/DAZ 3D/InstallManager/ManifestFiles/IM00013176-45_InteractiveLessonsforDAZStudio410.dsx
C:/Daz 3D/Applications/64-bit/DAZ 3D/DAZStudio4
```

```
find C:/ -name '*Daz to Blender*'
C:/Daz 3D/Applications/64-bit/DAZ 3D/DAZStudio4/docs/Plugins/Daz to Blender
C:/Daz 3D/Applications/64-bit/DAZ 3D/DAZStudio4/docs/Plugins/Daz to Blender/Daz to Blender.dsx
```

```
dir C:/Daz\ 3D/Applications/64-bit/DAZ\ 3D/DAZStudio4/scripts/support/DAZ/
ContentCreatorToolkit  dzContentDirectoryManager.dse		      dzExportProductMetadata.dse  dzNodePostCreate.dse		 dzUpdateMergeMenus.dse  ScriptedRenderer
Contributors	       dzCustomActionLoadFile.dse		      dzHandleURL.dse		   dzPowerLoader		 rendertime		 shaderDefinitions
dForce		       dzCustomActionShowContentLibraryContainer.dse  dzMDLDirectoryManager.dse    dzRenderDirectoryManager.dse  SceneBuilder		 Uber
```

Could you please provide steps for installing on the latest Daz Studio?

**Comment by butaixianran** [comment]
Hi, I think you are following the old installation document.   

Check this part of readme document:
[https://github.com/butaixianran/DazToBlender#maunal-installation](https://github.com/butaixianran/DazToBlender#maunal-installation)  

Basically, you just create a new folder in your Daz library's script folder, then copy these daz scripts into it. 
When exporting, just run it in your content library, like any other daz script.

Or, you can just use Daz's official DTB 2022 at Daz side, and use our blender addon at blender side.

**Comment by UuuNyaa** [comment]
Thank you for your effort 😃
I will try with official DTB 2022.
